### ISSUE TITLE
RequestError: Buffer is not defined

### ISSUE THREAD

**Issue by Jayphen** [romgrk/todoist.nvim#1]
Hey, thanks for your work on this.

I've just installed the plugin, run `npm install` in the plugin dir and then run `UpdateRemotePlugins` in neovim. When I try to execute `:TodoistInit` I get the error mentioned in the title.

NVIM v0.4.3
node v12.16.1

**Comment by 20jam** [comment]
I have this issue too, Buffer is not defined.

**Comment by romgrk** [comment]
Damn right! Forgot to mention it on the readme but there is a bug in the upstream neovim node-client. I think the issue starts with nodejs 12, so I'd try using node 11 or lower until https://github.com/neovim/node-client/pull/143 is published to npm.

Alternatively, on my machine I installed the `neovim` package from git master instead of npm. You could try:
```sh
npm uninstall -g neovim

git clone https://github.com/neovim/node-client
cd node-client/packages/neovim
npm install
npm build
npm link
```

**Comment by 20jam** [comment]
I’ll try that and report back.

**Comment by Jayphen** [comment]
Installing node-client from github seemed to solve the issue

**Comment by romgrk** [comment]
Good news! The maintainer of the `neovim` package kindly agreed to release a new version of the package with the fix included, so you should now be able to install it the normal way (from npm). Please re-open if you still observe the issue after updating :)
